import { Exhaustive } from "@/types";
import { ProjectError } from "../errors";

//  todo: add docs
export const ProjectErrorStatusCodeMap: Exhaustive<ProjectError.ErrorName> = {
  EXCEEDED_MAX_FETCH_RETRIES_ERROR: 500,
  EMPTY_PROJECTS_TABLE_ERROR: 500,
  DB_FETCH_ERROR: 500,
  RETRIEVE_PROJECTS_ERROR: 500,
  RESOLVE_PROJECTS_ERROR: 500,
  LOAD_FROM_CACHE_ERROR: 500,
  LOAD_BACKUP_ERROR: 500,
  CREATE_NEW_CACHE_ERROR: 500,
  STORE_CACHE_PAGE_ERROR: 500,
  BACKUP_CACHE_READONLY_MODIFICATION_ERROR: 500,
  MISSING_PROJECT_IN_PAGE_ERROR: 404,
  //  Inherited PageError types
  PAGE_OUT_OF_BOUNDS_ERROR: 404,
  MISSING_PAGE_ERROR: 404,
  PAGE_RETRIEVAL_ERROR: 500,
} as const;
